### ISSUE TITLE
GPL vs MIT?

### ISSUE THREAD

**Issue by a-c-m** [genixpro/socket.io-amqp#1]
Hi there,

We are considering using this module but GPL 3 is not compatible with our legal department :) Are you fixed on GPL or would you consider changing to MIT? http://choosealicense.com/

Thanks

**Comment by genixpro** [comment]
Well your legal department sucks. They are also probably wrong in their
interpretation of GPL provisions as they apply to your company. License
issues almost never come up in practice in server software because people
don't distribute binaries of their websites. Also, I use LGPL, not plain
GPL, which permits you to link and use socket.io-amqp in your software,
even proprietary and distributed, provided you include a copy of the LGPL
license in reference to the module. LGPL is much more permissive then plain
GPL.

Frankly, if you are planning taking my code and relicensing it, then I
would have issue with that. I released the software as open source and I
want it to stay that way, hence using GPL.

I could be convinced otherwise but I need a good reason.

---

Bradley Arsenault < bradley.allen.arsenault@gmail.com >
647-261-0462
Toronto, Ontario

**Comment by a-c-m** [comment]
A apologies - you are, of course 100% correct.

I only scanned the licence and panicked at GPL3 without seeing the LGPL part.  Consider myself suitably embarrassed and back in my box.

**Comment by genixpro** [comment]
You are wise to check the licenses on the tools you use. I almost never do
- my application probably breaks a few laws. No one has bitched yet though.

I hope the library proves useful to you as it has for me.

---

Bradley Arsenault < bradley.allen.arsenault@gmail.com >
647-261-0462
Toronto, Ontario
